baseURL: https://jasongrafmiller.netlify.app/
languageCode: en
DefaultContentLanguage: en
title: Website of Jason Grafmiller
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
taxonomies:
  category: categories
  series: series
  tag: tags
related:
  includeNewer: yes
  indices:
    - name: keywords
      weight: 100
    - name: tags
      weight: 80
  threshold: 80
  toLower: yes
