  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Publications"
  weight = 200
  identifier = "publications"
  url = "/publications/"

  [[main]]
  name = "Teaching"
  weight = 300
  identifier = "teaching"
  url = "/teaching/"

  [[main]]
  name = "Tutorials"
  weight = 400
  identifier = "tutorials"
  url = "/portfolio/"

  [[main]]
  name = "CV"
  weight = 500
  identifier = "tutorials"
  url = "/pdfs/Grafmiller_CV.pdf"


  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"