  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Publications"
  weight = 200
  identifier = "publications"
  url = "/publications/"

  [[main]]
  name = "Tutorials"
  weight = 400
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Teaching"
  weight = 300
  identifier = "teaching"
  url = "/teaching/"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"